apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-attendance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qr-attendance-app
  template:
    metadata:
      labels:
        app: qr-attendance-app
    spec:
      containers:
        - name: qr-attendance-app
          image: ghcr.io/juandev-mx/qr-attendance-system-professional:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80