services:
  app:
    image: docker-app:latest
    container_name: qr-attendance-app
    ports:
      - "8080:80"
  
    depends_on:
      - mysql
    networks:
      - qr-network

  mysql:
    image: mysql:8.0
    container_name: qr-attendance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: control_asistencias_qr
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - qr-network

  prometheus:
    image: prom/prometheus:latest
    container_name: qr-attendance-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
    depends_on:
      - app
      - alertmanager
    networks:
      - qr-network

  grafana:
    image: grafana/grafana:latest
    container_name: qr-attendance-grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - qr-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/am_config.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - qr-network

volumes:
  mysql_data:
  grafana_data:

networks:
  qr-network:
    driver: bridge
