services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: qr-attendance-app
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: qr-attendance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: control_asistencias_qr
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: qr-attendance-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: qr-attendance-grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  mysql_data:
  grafana_data:

