global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'adminempresa@gmail.com'
  smtp_auth_username: 'adminempresa@gmail.com'
  smtp_auth_password: 'contraseña123' 

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'gmail-alerts'

receivers:
- name: 'gmail-alerts'
  email_configs:
  - to: 'adminempresa@gmail.com'
    send_resolved: true
    headers:
      subject: '{{ .Status | toUpper }} - {{ .CommonLabels.alertname }}'

